#!/bin/bash

set -eo pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

export PATH=/usr/local/bin:$PATH

PAYLOAD=$(mktemp $TMPDIR/codeclimate-resource-request.XXXXXX)

cat > $PAYLOAD <&0

COVERPROFILE=$(jq -r '(.params.coverage_file // "cover.out")' < $PAYLOAD)
INPUT_TYPE=$(jq -r '(.params.input_type // "gocov")' < $PAYLOAD)
PREFIX=$(jq -r '(.params.prefix // "")' < $PAYLOAD)
SOURCE_PATH=$(jq -r '(.params.source_path // "")' < $PAYLOAD)

token=$(jq -r '(.source.api_token // "")' < $PAYLOAD)
if [ ! -z "${PREFIX}" ]; then
    prefixargs="-p ${PREFIX}"
fi

pushd $1/$SOURCE_PATH
    cc-test-reporter format-coverage $prefixargs -t $INPUT_TYPE $COVERPROFILE
    CC_TEST_REPORTER_ID=$token cc-test-reporter upload-coverage || true
popd

timestamp="$(jq -n "{version:{timestamp:\"$(date +%s)\"}}")"
echo "$timestamp" | jq -s add >&3
